# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d31f4619c0111d84a46c81f349f6896a3494d08ea37792a73d086a2dc7b419c9016914533d69d71698b3722a76fd1c387e622ffecf73a83b0c24ce6ff3a3fae3
  fb_app_id: 441889169342338
  fb_app_secret: <%= ENV['AAP_TRACKER_FB_APP_SECRET'] %>
  fb_volunters_group_id: 1207068475988618
  fb_officials_group_id: 1027382157303514

test:
  secret_key_base: 02e770a8e51e754bc1165d01c09ed534b7ecf0109079a567eedcc9f60e66147f2bb9a60b06d56a5aabb6205ac439053a7dd6ed42b5e86502d645982640b419eb
  fb_app_id: 441889169342338
  fb_app_secret: <%= ENV['AAP_TRACKER_FB_APP_SECRET'] %>
  fb_volunters_group_id: 1207068475988618
  fb_officials_group_id: 1027382157303514

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  fb_app_id: <%= ENV['FB_APP_ID'] %>
  fb_app_secret: <%= ENV['FB_APP_SECRET'] %>
  fb_volunters_group_id: <%= ENV['FB_VOLUNTEERS_GROUP_ID'] %>
  fb_officials_group_id: <%= ENV['FB_OFFICIALS_GROUP_ID'] %>
